#!/system/bin/sh
# Init.d support

export PATH=/sbin:/system/sbin:/system/bin:/system/xbin

# Run our scripts first
for i in /Optimized/scripts/*; do
	$i;
done

# Run scripts inside init.d
chmod -R 755 /system/etc/init.d
for i in /system/etc/init.d/*; do
	$i;
done
